apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: game-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: game-app
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
